### PR TITLE
Update btt_skr_mini_e3_2.0_alt2_map.h

### PR DESCRIPTION
**Pull request by MeKeCNC**

### CODE REVIEW

**Comment by MeKeCNC** [comment]
> A new (alternative) board map should be added instead as this change will require rewiring of machines for those who use the current map? E.g. -> btt_skr_mini_e3_2.0_alt2_map.h?

it could be but, how do you do this option on the web-based compilation page?

**Comment by terjeio** [comment]
> how do you do this option on the web-based compilation page?

Boards are added for the Web Builder in [this file](https://github.com/grblHAL/STM32F1xx/blob/master/driver.json).

**Comment by MeKeCNC** [comment]
> btt_skr_mini_e3_2.0_alt2_map.h?

I know this board has supported, my question is, there may be two different CPU map files for your suggestion, how do I select it during web based compilation?

**Comment by terjeio** [comment]
> how do I select it during web based compilation?

When adding it to the _driver.json_ file linked to above it will appear in the board drop-down.

**Comment by terjeio** [comment]
Patched manually due to beeing incomplete.

**Pull request closed without merging**
